document.writeln("<link rel=\'stylesheet\' href=\'../css/navi_css.css\'>");
document.writeln("    	<div class=\'container-fiuled\' id=\'row1\'>");
document.writeln("			<div class=\'row clearfix\'>");
document.writeln("				<div class=\'col-md-12 column\'>");
document.writeln("					<nav class=\'navbar navbar-expand-sm\' role=\'navigation\'>");
document.writeln("						<div class=\'navbar-header\'>");
document.writeln("							<a class=\'navbar-brand\' href=\'#\'>");
document.writeln("								<img alt=\'logo\' width=\'180px\' src=\'/meowcat/image/logo1.png\' />");
document.writeln("							</a>");
document.writeln("						</div>");
document.writeln("							<ul class=\'nav navbar-nav pull-right\'>");
document.writeln("								<li class=\'dropdown\'>");
document.writeln("									<a href=\'#\' class=\'dropdown-toggle\' data-toggle=\'dropdown\'>开始工作<strong class=\'caret\'></strong></a>");
document.writeln("									<ul class=\'dropdown-menu\'>");
document.writeln("										<li>");
document.writeln("											<a href=\'#\'>团队项目</a>");
document.writeln("										</li>");
document.writeln("										<li>");
document.writeln("									 		<a href=\'#\'>人员管理</a>");
document.writeln("										</li>");
document.writeln("									</ul>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\'#\'>PM档案</a>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\'#\'>注销</a>");
document.writeln("								</li>");
document.writeln("							</ul>");
document.writeln("");
document.writeln("					</nav>");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("		</div>");
document.writeln("");
document.writeln("		<div class=\'container-fiuled\' >");
document.writeln("			<div class=\'row clearfix\'>");
document.writeln("				<div class=\'col-md-2 column\' id=\'row2col1\'>");
document.writeln("					<ul class=\'nav nav-stacked text-center\'>");
document.writeln("						<li>");
document.writeln("							<table id=\'table0\'>");
document.writeln("								<tr>");
document.writeln("									<td colspan=\'2\'>");
document.writeln("										<svg width=\'6em\' height=\'6em\' viewBox=\'0 0 16 16\' class=\'bi bi-person-circle\' fill=\'currentColor\' xmlns=\'http://www.w3.org/2000/svg\'>");
document.writeln("  											<path d=\'M13.468 12.37C12.758 11.226 11.195 10 8 10s-4.757 1.225-5.468 2.37A6.987 6.987 0 0 0 8 15a6.987 6.987 0 0 0 5.468-2.63z\'/>");
document.writeln("  											<path fill-rule=\'evenodd\' d=\'M8 9a3 3 0 1 0 0-6 3 3 0 0 0 0 6z\'/>");
document.writeln(" 											<path fill-rule=\'evenodd\' d=\'M8 1a7 7 0 1 0 0 14A7 7 0 0 0 8 1zM0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8z\'/>");
document.writeln("										</svg>");
document.writeln("									<td>");
document.writeln("								</tr>");
document.writeln("								<tr>");
document.writeln("									<td align=\'left\'>");
document.writeln("										用户名");
document.writeln("									</td>");
document.writeln("									<td align=\'right\'>");
document.writeln("										xxx");
document.writeln("									</td>");
document.writeln("								</tr>");
document.writeln("								<tr>");
document.writeln("									<td align=\'left\'>");
document.writeln("										用户ID");
document.writeln("									</td>");
document.writeln("									<td align=\'right\'>");
document.writeln("										xxxxxx");
document.writeln("									</td>");
document.writeln("								</tr>");
document.writeln("								<tr>");
document.writeln("									<td align=\'left\'>");
document.writeln("										邮箱");
document.writeln("									</td>");
document.writeln("									<td align=\'right\'>");
document.writeln("										xxxxx@xx.com");
document.writeln("									</td>");
document.writeln("								</tr>");
document.writeln("							</table>");
document.writeln("						</li>");
document.writeln("						<li class=\'row2-3\'>");
document.writeln("							<a href=\'#\'>文档列表</a>");
document.writeln("						</li>");
document.writeln("						<li class=\'row2-3\'>");
document.writeln("							<a href=\'#\'>术语库</a>");
document.writeln("						</li>");
document.writeln("						<li class=\'row2-3\'>");
document.writeln("							<a href=\'#\'>翻译记忆库</a>");
document.writeln("						</li>");
document.writeln("						<li class=\'row2-3\'>");
document.writeln("							<a href=\'#\'>机器翻译</a>");
document.writeln("						</li>");
document.writeln("						<li class=\'row2-3\'>");
document.writeln("							<a href=\'#\'>风格指南</a>");
document.writeln("						</li>");
document.writeln("						<li>");
document.writeln("							<a href=\'#\'>关于我们</a>");
document.writeln("						</li>");
document.writeln("					</ul>");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("		</div>");
document.writeln("<div class=\'container-fluid col-md-10 column\' style=\'margin-top:80px\'>");